import styles from './MainLayout.module.css'
import Navbar from '../Navbar'
import Head from 'next/head'
import { FC } from "react"

export const MainLayout: FC<{children: React.ReactNode}> = ({ children }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <main className={styles.main}>
                {children}
            </main>
        </div>
    )
}